- include: centos.yml
  when: ansible_os_family == "RedHat"
- include: debian.yml
  when: ansible_os_family == "Debian"
- name: wgrywanie configu
#  template: src=haproxy.cfg.jinja2 dest={{haproxy_conf}}
  template: src=haproxy.cfg.jinja2 dest=/etc/haproxy/haproxy.cfg
  notify: restart_haproxy
- name: uruchomienie haproxy
  service: name=haproxy state=started
- name: autostart haproxy
  service: name=haproxy enabled=yes
