---
- hosts: all
  gather_facts: false
  user: root
  tasks:
  - yum: name=python-pip state=latest
  - yum: name=gcc state=latest
  - yum: name=gcc-c++ state=latest
  - yum: name=python-devel state=latest
  - action: pip name=pyzmq state=present
  - action: pip name=pyasn1
  - action: pip name=PyCrypto 
  - action: pip name=python-keyczar
  - yum: name=zeromq state=latest
  - action: fireball
