---
- hosts: http
#  accelerate: true
#  connection: paramiko
  roles:
  - http
- hosts: director
  roles:
  - director
- hosts: haproxy
#  accelerate: true
#  connection: paramiko
  roles:
  - haproxy
- hosts: realserver
  roles:
  - realserver

- host: worker
  roles:
  - worker
