---
- hosts: all
  tasks:
  - ping:
    tags: configure
- hosts: datastore
  roles:
  - datastore
- hosts: all
  roles:
  - common
- hosts: workers
  roles:
  - worker
- hosts: http
  roles:
  - http
- hosts: haproxy
  roles:
  - haproxy
- hosts: realserver
  roles:
  - realserver
- hosts: director
  roles:
  - director

