- name: wgrywanie check_szz_cpu.sh
  copy: src=check_szz_cpu.sh dest=/usr/lib/nagios/plugins/ mode=755
  tags:
  - files
#- name: wgrywanie restart_nginx.sh
#  copy: src=restart_nginx.sh dest=/usr/lib/nagios/handlers/ mode=755
#  tags:
#  - files
