- name: wgrywanie commandsów
  copy: src=szz_commands.cfg dest=/etc/nagios/nrpe.d/
  notify: restart-nrpe
- name: zezwalanie na odpytywanie przez monitoring
  lineinfile: dest=/etc/nagios/nrpe.cfg regexp=^allowed_hosts= line=allowed_hosts=127.0.0.1,10.13.0.0/24
  notify: restart-nrpe
- name: dont_blame_nrpe=1
  lineinfile: dest=/etc/nagios/nrpe.cfg regexp=^dont_blame_nrpe line=dont_blame_nrpe=1
  notify: restart-nrpe

