- name: dodanie repo testing
  copy: src=test.list dest=/etc/apt/sources.list.d/test.list
  notify: apt_update
- name: instalacja oprogramowania
  apt: name={{item}} state=latest
  with_items:
  - nagios-nrpe-server
  - sysstat
  - bc
  - sudo
  - rsyslog
- name: uruchamianie aplikacji
  service: name=nagios-nrpe-server enabled=True state=running
  with_items:
  - nagios-nrpe-server
  - sysstat
  - rsyslog
  - crond
