- include_vars: "{{ ansible_os_family }}.yml"
  tags:
  - config
- include: centos.yml
  when: ansible_os_family == "RedHat"
- include: debian.yml
  when: ansible_os_family == "Debian"
- name: uruchamianie aplikacji
  service: name={{item}} enabled=True state=running
  with_items: run_apps
- include: checks.yml
- include: config.yml
